Add Authereum integration
wearekickback/app pull request #156
Opened 2019-08-08 23:15 UTC by cwhinfrey

2019-08-09 08:30 UTC, makoto commented on src/App.js
> +injectWeb3('rinkeby')
Can this be injected only at App.js? I think we need to inject somewhere we can pass the network name (eg: https://github.com/wearekickback/app/blob/dev/src/api/web3.js#L112)

2019-08-09 11:54 UTC, hiddentao commented
This needs discussion - all our network detection and resolution work happens in https://github.com/wearekickback/app/blob/dev/src/api/web3.js

Ideally this needs to integrate with that.

2019-10-04 05:06 UTC, jefflau requested changes

2019-10-04 05:06 UTC, jefflau commented on src/components/Header/AuthereumButton.js
> +  margin-bottom: -42.5px;
Integers only for pixel values. They'll be rounded anyway so let's make it explicit

2019-10-04 05:06 UTC, jefflau commented on src/components/Header/AuthereumButton.js
> +    margin-top: 17.5px;
Integer for pixels

2019-10-04 05:06 UTC, jefflau commented on src/components/Header/AuthereumButton.js
> +      return
Refactor as a functional component with hooks.

2019-10-04 05:06 UTC, jefflau commented on src/components/Header/AuthereumButton.js
> +      <GlobalConsumer>
Use a hook to consume the global context `useContext`

2019-10-04 05:06 UTC, jefflau commented on src/components/Header/AuthereumButton.js
> +      <GlobalConsumer>
https://reactjs.org/docs/hooks-reference.html#usecontext

2019-10-04 05:06 UTC, jefflau commented on src/components/Header/LogoutButton.js
> +  }
Use mq.small instead and reverse styles so it works with min-width

2019-10-04 05:06 UTC, jefflau commented on src/components/Modal/Modal.js
> +  }
Use mq.small instead and reverse styles so it works with min-width

2019-10-04 05:06 UTC, jefflau commented on src/components/Utils/LoadingDots.js
> +import styled from 'styled-components'
Remove in favour of react-emotion

2019-10-04 05:06 UTC, jefflau commented on src/components/Utils/LoadingDots.js
> +import styled from 'styled-components'
Pretty cool loading component!

2019-10-04 05:06 UTC, jefflau commented on src/components/svg/authereum.svg
> +4 -926 10 -992 44 -462 244 -900 578 -1264 76 -83 1282 -1134 1316 -1147 14
Run through SVGOMG:

https://jakearchibald.github.io/svgomg/

2019-10-04 05:06 UTC, jefflau commented on src/components/svg/metamask.svg
> +<g>
Run through https://jakearchibald.github.io/svgomg/

2019-10-04 05:06 UTC, jefflau commented on src/components/svg/ul.svg
> +<svg id="svg" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="400" viewBox="0, 0, 400,400"><g id="svgg"><path id="path0" d="M394.476 28
Run through https://jakearchibald.github.io/svgomg/

2019-10-04 05:08 UTC, jefflau commented on src/components/Auth/WalletModal.js
> +    console.log('TODO')
remove console.log

2019-11-29 03:47 UTC, jefflau commented
Thanks for making those changes. Do you mind taking a look at the media queries. I think you've got them the wrong way around as you just switched out `@media(max-width)` with `mq.small`, but our `mq.small` uses min-width.

Can you also take a look at the merge conflicts so we get this merged in?

Thanks

2019-11-29 05:19 UTC, jefflau commented
Had a go at merging this and trying to get things working. Had some issues with a module not being found inside the npm package `authereum` so I tried to update to the latest authereum beta, but when I click on logging in, nothing seems to happen.

(last couple commits merged incorrectly so can be removed if you need to)

2019-12-06 15:25 UTC, makoto commented on public/_redirects
> +/*    /index.html   200
no new line at the end of file

2019-12-06 15:27 UTC, makoto commented on src/assets/authereum_shield.svg
> + "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd"><svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="794.6667" height="794.6667" viewBox="0 0 596 596"><metadata>Created by potrace
no new line at the end of file

2019-12-06 15:29 UTC, makoto commented on src/components/Header/SignInButton.js
> +            {/* <LogoutButton /> */}
Is this comment necessary?

2019-12-06 16:18 UTC, makoto commented on src/layout/Header.js
> +            <LogoutButton />
<img width="180" alt="Screenshot 2019-12-06 at 15 20 01" src="https://user-images.githubusercontent.com/2630/70337968-f0337100-1843-11ea-8240-6ae173d2013e.png">

I think we need a bit of gap between the button and sign in button

2019-12-06 16:24 UTC, makoto commented on package.json
> +    "authereum": "0.0.4-beta.55",
When I do `yarn deploy:pr` it fails to install npm module.

```
$yarn deploy:pr
yarn run v1.15.2
$ yarn build:release:kovan && scripts/deployTravisBuildToSurge.sh
$ yarn setup --kovan && yarn build
$ scripts/setup.js --kovan
{
  "DEPLOYER_CONTRACT_ADDRESS": "0xB7465Eef8d3334E1f78Af0382201bd079E3d926B",
  "API_URL": "https://kovan.api.kickback.events",
  "NUM_CONFIRMATIONS": 1,
  "ENV": "kovan",
  "DAI_CONTRACT_ADDRESS": "0x1246Ddaf0885A87D9F3DdF0f08d8B6cc57b68c5f",
  "GIT_COMMIT": "ac82ceb13be9c24f8d226149c29084bbc7aae537",
  "LOGROCKET_TOKEN": "",
  "ROLLBAR_TOKEN": "",
  "BLOCKNATIVE_DAPPID": ""
}
$ react-scripts build
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Failed to compile.

./src/api/web3.js
Cannot find module: 'authereum'. Make sure this package is installed.

You can install this package by running: yarn add authereum.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2019-12-06 16:30 UTC, makoto commented on src/config/index.js
> +// }
Please remove comments if you don't need it.

2019-12-06 16:30 UTC, makoto commented on src/components/svg/authereum.svg
> + "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd"><svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="794.6667" height="794.6667" viewBox="0 0 596 596"><metadata>Created by potrace
no new line at the end of file

2020-10-09 14:07 UTC, closed without merging